# Generated by Django 5.1.6 on 2025-02-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_symptom_remedy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='symptoms',
            field=models.ManyToManyField(related_name='customers', to='app.symptom'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.remedy')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staf')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.symptom')),
            ],
        ),
    ]
