# Generated by Django 5.1.6 on 2025-02-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_symptoms_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf',
            name='expertise',
            field=models.ManyToManyField(related_name='staff_experts', to='app.symptom'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
