# Generated by Django 5.1.5 on 2025-02-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
