# Generated by Django 5.1.5 on 2025-02-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_customer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plagarismchat",
            old_name="user",
            new_name="customer",
        ),
    ]
