# Generated by Django 5.1.6 on 2025-02-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_booking_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
