# Generated by Django 5.1.6 on 2025-03-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_plagarismchat_customer'),
        ('app', '0016_remove_booking_customer_booking_customer_contact_and_more'),
    ]

    operations = [
    ]
