# Generated by Django 5.1.6 on 2025-03-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20250311_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
