# Generated by Django 5.1.6 on 2025-03-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_booking_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.customer'),
            preserve_default=False,
        ),
    ]
